/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.84 95/04/20 12:46:03 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define FLEX_DEBUG
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;

#define FLEX_DEBUG
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 65
#define YY_END_OF_BUFFER 66
static yyconst short int yy_accept[138] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,   12,   12,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   66,   65,    1,    9,    2,    3,    8,    6,
        9,    9,    5,    4,   12,   11,   13,   18,   17,   14,
       65,   40,   19,   20,   39,   36,   40,   23,   23,   39,
       24,   23,   32,   21,   35,   39,   24,   45,   45,   64,
       63,   46,   65,    2,    3,    5,    7,    4,   12,   11,
       10,   18,   17,   16,   15,   19,   20,   39,   39,   37,
       30,    0,   31,   28,    0,   27,    0,   25,   39,   32,
       24,   34,   33,   21,   22,   39,   39,   44,   42,   44,

       41,   44,   64,   62,   47,   51,   62,   62,   62,   48,
       53,   54,   55,   56,   57,   58,   59,   60,   61,   62,
       38,   29,   26,   33,   42,   41,   43,   51,   50,   48,
       49,   52,   42,   43,   51,   52,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    4,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    8,    5,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   19,   19,
       19,   19,   19,   19,   19,   20,   20,    5,   21,    5,
        5,    5,   22,   23,   24,   25,   26,   25,   25,   25,
       27,   28,   27,   27,   27,   27,   29,   27,   27,   27,
       27,   27,   28,   27,   27,   27,   27,   27,   27,   27,
       30,   31,   12,   32,   27,   33,   34,   35,   25,   36,

       37,   38,   27,   27,   27,   27,   27,   27,   27,   39,
       27,   27,   27,   40,   28,   41,   27,   42,   27,   43,
       27,   27,   44,    5,   44,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,

        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5
    } ;

static yyconst int yy_meta[45] =
    {   0,
        1,    1,    2,    1,    3,    4,    1,    3,    3,    1,
        1,    1,    5,    3,    3,    3,    3,    3,    6,    6,
        1,    1,    3,    6,    6,    6,    7,    7,    7,    1,
        8,    3,    3,    6,    6,    6,    6,    6,    7,    7,
        7,    7,    7,    3
    } ;

static yyconst short int yy_base[159] =
    {   0,
      209,  208,    0,    0,    0,    0,    0,    0,   42,   43,
       44,   45,   76,    0,  118,  119,  120,  121,    0,    0,
        0,    0,  208,  433,  433,  433,   50,   55,  433,  433,
       41,  194,   43,    0,    0,    0,  188,    0,    0,  433,
      202,  433,   62,   63,  173,  433,  147,  188,  433,  111,
      112,  113,  117,  199,  433,  179,  167,  433,  192,    0,
      433,  433,  233,   66,   67,   53,  433,    0,    0,    0,
      433,    0,    0,  433,  433,  136,  137,  166,  276,  433,
      433,  190,  433,  433,  126,  433,  165,  433,  140,  144,
      163,  147,  153,  190,  433,  161,    0,  433,  163,  160,

      433,    0,    0,  433,  433,  155,  149,  146,  138,  433,
      433,  433,  433,  433,  433,  433,  433,  433,  433,    0,
      433,  149,  433,  168,  128,  433,    0,  106,  433,  433,
      433,    0,  433,  433,  433,  433,  433,  307,  315,  323,
      331,  339,  342,  349,  357,  365,  372,  379,  385,  393,
      401,  409,  417,  424,   68,   52,   47,   43
    } ;

static yyconst short int yy_def[159] =
    {   0,
      138,  138,  138,  138,  138,  138,  137,    7,  139,  139,
      140,  140,  137,   13,  141,  141,  142,  142,  138,  138,
      138,  138,  137,  137,  137,  137,  137,  137,  137,  137,
      137,  137,  137,  143,  144,  145,  137,  146,  147,  137,
      148,  137,  137,  137,  149,  137,  137,  137,  137,  149,
      149,  149,  149,  150,  137,  151,  149,  137,  152,  153,
      137,  137,  154,  137,  137,  137,  137,  143,  144,  145,
      137,  146,  147,  137,  137,  137,  137,  149,  151,  137,
      137,  137,  137,  137,  137,  137,  137,  137,  149,  149,
      149,  149,  149,  150,  137,  149,   79,  137,  137,  137,

      137,  155,  153,  137,  137,  137,  137,  137,  137,  137,
      137,  137,  137,  137,  137,  137,  137,  137,  137,  156,
      137,  137,  137,  149,  137,  137,  157,  137,  137,  137,
      137,  158,  137,  137,  137,  137,    0,  137,  137,  137,
      137,  137,  137,  137,  137,  137,  137,  137,  137,  137,
      137,  137,  137,  137,  137,  137,  137,  137
    } ;

static yyconst short int yy_nxt[478] =
    {   0,
       26,   27,   28,   27,   26,   29,   26,   26,   26,   26,
       30,   30,   26,   26,   26,   31,   26,   32,   33,   33,
       26,   26,   26,   34,   34,   34,   34,   34,   34,   30,
       26,   26,   26,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   30,   36,   36,   39,   39,  136,   40,
       40,   64,  134,   64,   37,   37,   65,  132,   65,   66,
       66,   66,   66,   76,   77,   76,   77,   64,   65,   64,
       65,   66,   66,  127,   41,   41,   42,   43,   44,   43,
       45,   46,   47,   45,   45,   48,   49,   49,   45,   50,
       51,   50,   52,   45,   53,   53,   54,   55,   45,   45,

       45,   45,   45,   45,   45,   49,   56,   45,   57,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       24,   24,   61,   61,  135,   62,   62,   89,   91,   90,
       90,   92,   92,   93,   91,   90,   90,   76,   77,   76,
       77,   79,   79,   79,  122,  122,  133,   79,   59,   59,
       63,   63,   80,  131,   81,   82,   83,   84,   92,   92,
       93,  130,   90,   90,  129,   92,   92,  122,  122,   85,
       79,  124,  124,  128,   79,  126,   86,   79,   87,   78,
       78,  125,   78,   79,   78,   78,  124,  124,   78,   78,
       78,   79,   95,   79,  123,  121,   79,   79,   79,   78,

       78,   95,   88,   79,   75,   71,   67,  137,   78,   97,
       99,   25,   25,  137,  137,  100,  137,  100,  137,  100,
      100,  137,  137,  101,  137,  137,  137,  137,  137,  137,
      137,  137,  137,  137,  102,  105,  137,  137,  137,  137,
      137,  137,  137,  137,  137,  137,  137,  137,  137,  137,
      137,  106,  137,  137,  137,  137,  107,  137,  108,  137,
      107,  109,  137,  137,  110,  137,  111,  112,  113,  114,
      115,  116,  117,  118,  119,  120,   78,   78,  137,   78,
      137,   78,   78,  137,  137,   78,   78,   78,  137,  137,
      137,  137,  137,  137,  137,  137,   78,   78,  137,  137,

      137,  137,  137,  137,  137,   78,   97,   24,   24,   24,
       24,   24,   24,   24,   24,   35,   35,   35,   35,   35,
       35,   35,   35,   38,   38,   38,   38,   38,   38,   38,
       38,   58,   58,   58,   58,   58,   58,   58,   58,   60,
       60,   60,   60,   60,   60,   60,   60,   68,   68,   69,
      137,   69,   69,  137,   69,   69,   69,   70,  137,   70,
       70,  137,   70,   70,   70,   72,  137,   72,  137,   72,
       72,   72,   73,  137,   73,  137,   73,   73,   73,   74,
       74,   74,   74,   74,   74,   74,   74,   78,  137,   78,
       78,   78,   78,   94,   94,   94,   94,   94,   94,   94,

       94,   96,  137,   96,   96,   96,   96,   96,   96,   98,
      137,   98,   98,   98,   98,   98,   98,  103,  137,  103,
      137,  103,  103,  103,  104,  104,  104,  104,  104,  104,
      104,  104,   23,  137,  137,  137,  137,  137,  137,  137,
      137,  137,  137,  137,  137,  137,  137,  137,  137,  137,
      137,  137,  137,  137,  137,  137,  137,  137,  137,  137,
      137,  137,  137,  137,  137,  137,  137,  137,  137,  137,
      137,  137,  137,  137,  137,  137,  137
    } ;

static yyconst short int yy_chk[478] =
    {   0,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    9,   10,   11,   12,  158,   11,
       12,   27,  157,   27,    9,   10,   28,  156,   28,   31,
       31,   33,   33,   43,   44,   43,   44,   64,   65,   64,
       65,   66,   66,  155,   11,   12,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,

       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       15,   16,   17,   18,  128,   17,   18,   50,   51,   50,
       50,   52,   52,   53,   51,   53,   53,   76,   77,   76,
       77,   50,   51,   52,   85,   85,  125,   53,   15,   16,
       17,   18,   47,  109,   47,   47,   47,   47,   89,   89,
       90,  108,   90,   90,  107,   92,   92,  122,  122,   47,
       89,   93,   93,  106,   90,  100,   47,   92,   47,   56,
       56,   99,   56,   93,   56,   56,  124,  124,   56,   56,
       56,   96,   94,   91,   87,   82,   78,   57,  124,   56,

       56,   54,   48,   45,   41,   37,   32,   23,   56,   56,
       59,    2,    1,    0,    0,   59,    0,   59,    0,   59,
       59,    0,    0,   59,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   59,   63,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   63,    0,    0,    0,    0,   63,    0,   63,    0,
       63,   63,    0,    0,   63,    0,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   79,   79,    0,   79,
        0,   79,   79,    0,    0,   79,   79,   79,    0,    0,
        0,    0,    0,    0,    0,    0,   79,   79,    0,    0,

        0,    0,    0,    0,    0,   79,   79,  138,  138,  138,
      138,  138,  138,  138,  138,  139,  139,  139,  139,  139,
      139,  139,  139,  140,  140,  140,  140,  140,  140,  140,
      140,  141,  141,  141,  141,  141,  141,  141,  141,  142,
      142,  142,  142,  142,  142,  142,  142,  143,  143,  144,
        0,  144,  144,    0,  144,  144,  144,  145,    0,  145,
      145,    0,  145,  145,  145,  146,    0,  146,    0,  146,
      146,  146,  147,    0,  147,    0,  147,  147,  147,  148,
      148,  148,  148,  148,  148,  148,  148,  149,    0,  149,
      149,  149,  149,  150,  150,  150,  150,  150,  150,  150,

      150,  151,    0,  151,  151,  151,  151,  151,  151,  152,
        0,  152,  152,  152,  152,  152,  152,  153,    0,  153,
        0,  153,  153,  153,  154,  154,  154,  154,  154,  154,
      154,  154,  137,  137,  137,  137,  137,  137,  137,  137,
      137,  137,  137,  137,  137,  137,  137,  137,  137,  137,
      137,  137,  137,  137,  137,  137,  137,  137,  137,  137,
      137,  137,  137,  137,  137,  137,  137,  137,  137,  137,
      137,  137,  137,  137,  137,  137,  137
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 1;

static yyconst short int yy_rule_linenum[65] =
    {   0,
       70,   75,   76,   77,   78,   79,   80,   81,   83,   89,
       90,   91,   92,   98,   99,  100,  101,  102,  108,  109,
      110,  111,  112,  114,  115,  117,  118,  119,  121,  133,
      134,  136,  137,  138,  140,  142,  143,  144,  146,  148,
      154,  156,  157,  158,  159,  165,  219,  220,  221,  222,
      225,  234,  248,  249,  250,  251,  252,  253,  254,  255,
      256,  257,  259,  261
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
char *yytext;
#line 1 "scanner.l"
#define INITIAL 0
/* Translatable strings extractor.
   Copyright (C) 1996 Free Software Foundation, Inc.
   François Pinard <pinard@iro.umontreal.ca>, 1996.  */
#line 6 "scanner.l"
#include <stdio.h>

#include "obstack.h"
#define obstack_chunk_alloc xmalloc
#define obstack_chunk_free free
void *xmalloc (int);

#include "xpot.h"
#include "parser.h"

/* Set to nonzero by parser when next string should be considered at
   translatable.  Always reset to zero by scanner before any return.  */
int translatable_flag;

/* Error reporting routine.  */
void yyerror (const char *);

/* Pool for all saved comment characters.  */
static struct obstack comment_stack;

/* Pool for all saved string characters.  */
static struct obstack string_stack;

/* Table used for making all strings unique.  */
static hash_table string_table;

/* Location for next scanning.  */
static const char *current_file_name;
static int current_line_number;

/* Location for last scanned string.  */
static const char *string_file_name;
static int string_line_number;

static int token_seen;		/* non-string token seen recently */
static int meta_flag;		/* if M- has been seen */
static int control_flag;	/* if C- has been seen */
static int escape_value;	/* character value of escaped sequence */
static char *last_comment;	/* comment preceeding the string */

static void save_elisp_comment (void);
static void begin_string_scan (int);
static void save_one_character (int);
static void unexpected_character (void);

#define ELISP_RETURN(Token) \
  do {				\
    token_seen = 1;		\
    translatable_flag = 0;	\
    return Token;		\
  } while (0)

#define STATE_AWK 1

#define STATE_BASH 2

#define STATE_C 3
#define STATE_C_COMMENT 4
#define STATE_C_STRING 5

#define STATE_ELISP 6
#define STATE_ELISP_CHARACTER 7
#define STATE_ELISP_STRING 8

#define STATE_PERL 9

#define STATE_PO 10

#line 603 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 69 "scanner.l"

#line 752 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 138 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 433 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */

		if ( yy_flex_debug )
			{
			if ( yy_act == 0 )
				fprintf( stderr, "--scanner backing up\n" );
			else if ( yy_act < 65 )
				fprintf( stderr, "--accepting rule at line %d (\"%s\")\n",
				         yy_rule_linenum[yy_act], yytext );
			else if ( yy_act == 65 )
				fprintf( stderr, "--accepting default rule (\"%s\")\n",
				         yytext );
			else if ( yy_act == 66 )
				fprintf( stderr, "--(end of buffer or a NUL)\n" );
			else
				fprintf( stderr, "--EOF (start condition %d)\n", YY_START );
			}

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 70 "scanner.l"

	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(STATE_AWK):
case YY_STATE_EOF(STATE_BASH):
case YY_STATE_EOF(STATE_C):
case YY_STATE_EOF(STATE_C_COMMENT):
case YY_STATE_EOF(STATE_C_STRING):
case YY_STATE_EOF(STATE_ELISP):
case YY_STATE_EOF(STATE_ELISP_CHARACTER):
case YY_STATE_EOF(STATE_ELISP_STRING):
case YY_STATE_EOF(STATE_PERL):
case YY_STATE_EOF(STATE_PO):
#line 71 "scanner.l"
ELISP_RETURN (0);
	YY_BREAK
/* C language */
case 2:
YY_RULE_SETUP
#line 75 "scanner.l"

	YY_BREAK
case 3:
YY_RULE_SETUP
#line 76 "scanner.l"
current_line_number++;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 77 "scanner.l"
token_seen = 1; return C_IDENTIFIER;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 78 "scanner.l"
token_seen = 1; return C_NUMBER;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 79 "scanner.l"
return yytext[0];
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 80 "scanner.l"
BEGIN STATE_C_COMMENT;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 81 "scanner.l"
BEGIN STATE_C_STRING;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 83 "scanner.l"
unexpected_character ();
	YY_BREAK

/* C - comment */
case 10:
YY_RULE_SETUP
#line 89 "scanner.l"
BEGIN STATE_C;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 90 "scanner.l"
current_line_number++;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 91 "scanner.l"

	YY_BREAK
case 13:
YY_RULE_SETUP
#line 92 "scanner.l"

	YY_BREAK

/* C - string */
case 14:
YY_RULE_SETUP
#line 98 "scanner.l"
BEGIN STATE_C; return C_STRING;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 99 "scanner.l"
current_line_number++;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 100 "scanner.l"

	YY_BREAK
case 17:
YY_RULE_SETUP
#line 101 "scanner.l"
current_line_number++;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 102 "scanner.l"

	YY_BREAK

/* Emacs LISP language */
case 19:
YY_RULE_SETUP
#line 108 "scanner.l"

	YY_BREAK
case 20:
YY_RULE_SETUP
#line 109 "scanner.l"
current_line_number++;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 110 "scanner.l"
save_elisp_comment ();
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 111 "scanner.l"
save_elisp_comment (); current_line_number++;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 112 "scanner.l"
ELISP_RETURN (yytext[0]);
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 114 "scanner.l"
/* Just ignore quasi-quotation, save for... */
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 115 "scanner.l"
ELISP_RETURN (ELISP_OTHER_ATOM);
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 117 "scanner.l"
ELISP_RETURN ('['); /* char-table */
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 118 "scanner.l"
ELISP_RETURN ('['); /* byte-code */
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 119 "scanner.l"
ELISP_RETURN ('('); /* text properties */
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 121 "scanner.l"
{
    int counter;
    int character;

    for (counter = atoi (yytext + 2); counter > 0; counter--)
      {
	character = input ();
	if (character == '\n')
	  current_line_number++;
      }
  }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 133 "scanner.l"
ELISP_RETURN (ELISP_OTHER_ATOM); /* docum from file */
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 134 "scanner.l"
ELISP_RETURN ('\''); /* function */
	YY_BREAK
case 32:
#line 137 "scanner.l"
case 33:
#line 138 "scanner.l"
case 34:
YY_RULE_SETUP
#line 138 "scanner.l"
ELISP_RETURN (ELISP_OTHER_ATOM); /* number */
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 140 "scanner.l"
BEGIN STATE_ELISP_CHARACTER;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 142 "scanner.l"
begin_string_scan (0); /* simple string */
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 143 "scanner.l"
begin_string_scan (1); /* translated string */
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 144 "scanner.l"
begin_string_scan (0); /* boolean vector */
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 146 "scanner.l"
ELISP_RETURN (ELISP_SYMBOL);
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 148 "scanner.l"
unexpected_character ();
	YY_BREAK

/* Emacs LISP - single character */
case 41:
YY_RULE_SETUP
#line 154 "scanner.l"

	YY_BREAK
case 42:
#line 157 "scanner.l"
case 43:
#line 158 "scanner.l"
case 44:
#line 159 "scanner.l"
case 45:
YY_RULE_SETUP
#line 159 "scanner.l"
BEGIN STATE_ELISP; ELISP_RETURN (ELISP_OTHER_ATOM);
	YY_BREAK

/* Emacs LISP - string of characters */
case 46:
YY_RULE_SETUP
#line 165 "scanner.l"
{
    if (token_seen)
      {
	/* Ignore a comment not immediately preceeding the string.  */
	obstack_free (&comment_stack, obstack_finish (&comment_stack));
	last_comment = NULL;
      }
    else
      {
	/* Complete the accumulated comment block.  */
	obstack_1grow (&comment_stack, '\0');
	last_comment = obstack_finish (&comment_stack);
	if (*last_comment == '\0')
	  {
	    /* Disregard the comment block if it contains nothing.  */
	    obstack_free (&comment_stack, obstack_finish (&comment_stack));
	    last_comment = NULL;
	  }
      }
    if (translatable_flag)
      {
	struct reference *reference = (struct reference *)
	  xmalloc (sizeof (struct reference));
	struct po_entry *po_entry;
	char *string;
	int length;

	obstack_1grow (&string_stack, '\0');
	string = obstack_finish (&string_stack);
	length = strlen (string);
	reference->file_name = string_file_name;
	reference->line_number = string_line_number;

	if (find_entry (&string_table, string, length, (void **) &po_entry) < 0)
	  {
	    reference->next = NULL;
	    po_entry = (struct po_entry *) xmalloc (sizeof (struct po_entry));
	    po_entry->next = po_entry_list;
	    po_entry->reference_list = reference;
	    po_entry->msgid = string;
	    po_entry_list = po_entry;
	    insert_entry (&string_table, string, length, po_entry);
	  }
	else
	  {
	    obstack_free (&string_stack, string);
	    reference->next = po_entry->reference_list;
	    po_entry->reference_list = reference;
	  }
      }
    BEGIN STATE_ELISP;
    ELISP_RETURN (ELISP_OTHER_ATOM);
  }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 219 "scanner.l"
current_line_number++;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 220 "scanner.l"
control_flag = 1;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 221 "scanner.l"
meta_flag = 1;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 222 "scanner.l"

	YY_BREAK
case 51:
YY_RULE_SETUP
#line 225 "scanner.l"
{
    int value = yytext[1] - '0';
    char *cursor = yytext + 2;

    while (*cursor)
      value = 8 * value + *cursor++ - '0';
    save_one_character (value);
  }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 234 "scanner.l"
{
    int value = 0;
    char *cursor = yytext + 2;

    while (*cursor)
      if (*cursor >= 'a' && *cursor <= 'f')
	value = 16 * value + *cursor++ - 'a' + 10;
      else if (*cursor >= 'A' && *cursor <= 'F')
	value = 16 * value + *cursor++ - 'A' + 10;
      else
	value = 16 * value + *cursor - '0';
    save_one_character (value);
  }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 248 "scanner.l"
save_one_character ('\007');
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 249 "scanner.l"
save_one_character ('\b');
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 250 "scanner.l"
save_one_character (127);
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 251 "scanner.l"
save_one_character (27);
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 252 "scanner.l"
save_one_character ('\f');
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 253 "scanner.l"
save_one_character ('\n');
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 254 "scanner.l"
save_one_character ('\r');
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 255 "scanner.l"
save_one_character ('\t');
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 256 "scanner.l"
save_one_character ('\v');
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 257 "scanner.l"
save_one_character (yytext[1]);
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 259 "scanner.l"
save_one_character ('\n'); current_line_number++;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 261 "scanner.l"
{
    if (control_flag || meta_flag)
      {
	save_one_character (yytext[0]);
	if (yyleng > 1 && translatable_flag)
	  obstack_grow (&string_stack, yytext + 1, yyleng - 1);
      }
    else if (translatable_flag)
      obstack_grow (&string_stack, yytext, yyleng);
  }
	YY_BREAK

case 65:
YY_RULE_SETUP
#line 274 "scanner.l"
ECHO;
	YY_BREAK
#line 1276 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a singled characater, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 138 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 138 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 137);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yytext_ptr = yy_c_buf_p;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						{
						yy_c_buf_p =
						yytext_ptr + YY_MORE_ADJ;
						return EOF;
						}

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;
					break;

				case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
					YY_FATAL_ERROR(
					"unexpected last match in yyinput()" );
#else
					YY_FATAL_ERROR(
					"unexpected last match in input()" );
#endif
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *str )
#else
YY_BUFFER_STATE yy_scan_string( str )
yyconst char *str;
#endif
	{
	int len;
	for ( len = 0; str[len]; ++len )
		;

	return yy_scan_bytes( str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n - YY_MORE_ADJ; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	return (void *) realloc( ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 274 "scanner.l"


/* Functions proper.  */

/*----------------------------------------------------------------------.
| Initialize the scanning of a FILE, which is already opened, and which |
| have NAME as its file name.					        |
`----------------------------------------------------------------------*/

void
initialize_scan (FILE *file, const char *name, enum language language)
{
  static int first_time = 1;

  if (first_time)
    {
      first_time = 0;

      if (!obstack_init (&comment_stack))
	error (EXIT_FAILURE, 0, _("Memory exhausted."));

      if (!obstack_init (&string_stack))
	error (EXIT_FAILURE, 0, _("Memory exhausted."));

      if (init_hash (&string_table, 1000) < 0)
	error (EXIT_FAILURE, 0, _("Memory exhausted."));
    }

#ifdef FLEX_DEBUG
  yy_flex_debug = debug_lex;
#endif
  yyin = file;
  current_file_name = name;
  current_line_number = 1;

  switch (language)
    {
    case LANGUAGE_AWK:
      BEGIN STATE_AWK;
      break;

    case LANGUAGE_BASH:
      BEGIN STATE_BASH;
      break;

    case LANGUAGE_C:
      BEGIN STATE_C;
      break;

    case LANGUAGE_ELISP:
      BEGIN STATE_ELISP;
      break;

    case LANGUAGE_PERL:
      BEGIN STATE_PERL;
      break;

    case LANGUAGE_PO:
      BEGIN STATE_PO;
      break;
    }

  last_comment = NULL;
  translatable_flag = 0;
  token_seen = 1;
}

/*------------------------.
| Terminate the scanner.  |
`------------------------*/

void
terminate_scan (void)
{
}

/*-------------------------------------------.
| Save or accumulate an Emacs LISP comment.  |
`-------------------------------------------*/

static void
save_elisp_comment (void)
{
  if (last_comment)
    {
      /* This is the first comment to appear after a string, which comment
	 the caller did not choose to save.  */
      obstack_free (&comment_stack, last_comment);
      last_comment = NULL;
    }
  else if (token_seen)
    /* This is the start of a new comment block.  */
    obstack_free (&comment_stack, obstack_finish (&comment_stack));
  /* Else, this is the continuation for an already started comment block.  */

  obstack_grow (&comment_stack, yytext, yyleng);
  token_seen = 0;
}

/*--------------------------------------------------------------.
| Prepare to scan string, knowing if it is to be TRANSLATABLE.  |
`--------------------------------------------------------------*/

static void
begin_string_scan (int translatable)
{
    string_file_name = current_file_name;
    string_line_number = current_line_number;
    if (translatable)
      translatable_flag = 1;
    meta_flag = 0;
    control_flag = 0;
    BEGIN STATE_ELISP_STRING;
}

/*-------------------------------------------------------------------.
| Accumulate a single character, subject to meta and control flags.  |
`-------------------------------------------------------------------*/

static void
save_one_character (int character)
{
  if (control_flag)
    {
      if (character == '?')
	character = ~(~0 << 7);
      else
	character &= ~(~0 << 5);
      control_flag = 0;
    }
  if (meta_flag)
    {
      character |= 1 << 7;
      meta_flag = 0;
    }
  if (translatable_flag)
    obstack_1grow (&string_stack, character);
}

/*--------------------------------.
| Diagnose an unknown character.  |
`--------------------------------*/

static void
unexpected_character (void)
{
  char message[80];

  sprintf (message, "Unexpected character: %d (%c)", yytext[0], yytext[0]);
  yyerror (message);
}

/*-----------------------------------------------.
| Report MESSAGE as a lexical or parsing error.	 |
`-----------------------------------------------*/

void
yyerror (const char *message)
{
  fprintf (stderr, "%s:%d: %s\n",
	   current_file_name, current_line_number, message);
}
